name = "Cheesepack"
author = "Jack Harrhy"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b82e7323cb470fccf840c261993391430024e316301f70dbf6b5fdbcb790903"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"
